services:
  - type: web
    name: paracasa
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://paracasa-backend.onrender.com/